[project]
name = "ecommerce"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Deepak Gupta", email = "deepak.gupta@kanishkasoftware.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.16.8",
]

[project.scripts]
ecommerce = "ecommerce:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
