"""add is_superadmin to users

Revision ID: 78096bc43066
Revises: 235ff83aba0e
Create Date: 2026-09-23 17:40:18.854547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78096bc43066'
down_revision: Union[str, Sequence[str], None] = '235ff83aba0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_unique_constraint('uq_tenant_category_name', 'category', ['tenant_id', 'name'])
    op.create_foreign_key(None, 'category', 'tenants', ['tenant_id'], ['id'])
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superadmin')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_constraint('uq_tenant_category_name', 'category', type_='unique')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.drop_column('category', 'tenant_id')
    # ### end Alembic commands ###
